# Generated by Django 4.2.6 on 2023-11-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='Product',
            new_name='product',
        ),
    ]
